[project]
name = "pyqt-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=2.3.0",
    "opencv-python>=4.12.0.88",
    "pyqt6==6.4.2",
    "setuptools>=80.9.0",
    "ultralytics>=8.3.212",
]
